pyEnable: true
pyLaunch: "python3"
pyPageSummary:
  allInOneStep: true
  allInOneStepScript: "tools_py/page-summary/auto-summary.py"
  summaryLength: 30
  model: 
    name: "csebuetnlp/mT5_multilingual_XLSum"
    max_length: 128
    min_length: 40
    length_penalty: 1.0
    num_beams: 4
    early_stopping: true
  threadMultiplicator: 4
  tokenizer:
    prompt: "summarize:"
    max_length: 512
    return_tensors: "tf"
    truncation: true
    skip_special_tokens: true
rawContentFolder: "doc-raw-contents"
preFlight: false
relatedPages:
  "enable": true
  "relPagesNo": 3
  "scoreLimit": -0.1
  "batchSize": 100
  "tf_idf_weigths": #sum of weights must be 1
    "keywords": 0.5
    "tags": 0.3
    "cats": 0.1
    "content": 0.1
autoExcerpt:
  keywords: 10
  minKeywordLength: 3
tagsToRemoveOnDryRender: ["script", "style", "h1", "h2", "h3", "h4", "h5", "h6"]
pySimilarPagesByContent:
  enable: true
  script: "tools_py/similar-pages/similar-pages.py"
  similarity_threshold: 0.6
  files_batch: 100
  chunk_size_in_files_batch: 100
  threadMultiplicator: 2 # safer to be >1 
  model_url: "https://tfhub.dev/google/universal-sentence-encoder/4"
pageKeywords:
  enable: true
github:
  enabled: true
  user: "pmc-community"
  repo: "jekyll-site-template"
  discussionOrg: "pmc-community"
  discussionsRepo: "discussions"
readingTime:
  enabled: true
  average_adult: 240        # Average adult reading speed
  comprehension_study: 200  # Study with focus on comprehension
  skimming_study: 300       # Speed reading or skimming
algoliaSearch:
  container: '#docsearch'
  debug: false
  maxResultsPerGroup: 20
  hitsPerPage: 10
  insights: true
  textHighlightPrefixTag: "<mark>" # prefix and postfix tags must be exactly as defined in Algolia DocSearch Index/Configuration/Hightlighting
  textHighlightPostfixTag: "</mark>"
  customIndexContentMaxSize: 500
  searchBtnLoadTimeout: 500
JTDSearch:
  searchBoxWidth: "fit-content"
changeLog:
  enabled: false
  history: 10
siteFooter:
  container: ".site-footer"
  rows:
    - content: "<div class=\"footer_first_row px-4 px-md-0\"><a href=\"https://innohub.space/eng/terms-of-service/\" target=_blank>Terms</a> | <a href=\"https://innohub.space/eng/privacy/\" target=_blank>Privacy</a> | <a href=\"https://innohub.space/eng/cookie-policy/\" target=_blank>Cookies</a></div>"
    - content: "<div class=\"footer_first_row  px-4 px-md-0\">Copyright <i class=\"bi bi-c-circle\"></i> <a href=\"https://pmc-expert.com\" target=_blank>PMC</a></div>"
googleAnalytics:
  enabled: true
  ga: "G-T86D5YQ5WF"
googleTagManager:
  enabled: true
  gtm: "GTM-KCLM93S"
breadcrumbs:
  depth: 100
hubspot:
  portalID: "7598952"
  region: "na1"
  feedbackFormID: 
    ID: "e166804c-61ea-4b51-801d-f4299cb5c06c"
faq:
  enabled: true
  pagination: true
  displayedPagesDesktop: 10
  displayedPagesMobile: 7
  perPage: 10
  faqToc: true
elements:
  figma:
    loadMessage: "INITIAL_LOAD"
    allowedUrl:
      - "https://www.figma.com"
      - "https://embed.figma.com"
      - "https://figma.com"