"/":
  enabled: true
  startPermalink: "/intro/"
  sections:
    header_section:
      title: "Documentation site framework"
      text: "Build your own documentation site without breaking a sweat! Let your users play boss and organize info however they want — neat, messy, or somewhere in between. And with lightning-fast search tools, finding what they need is quicker than you can say “Where’s that doc again?” Making docs easy, fun, and seriously powerful — all wrapped up in one neat package."
      startBtnText: "Overview"
      featuredMedia: "<img width=\"600\" height=\"auto\" src=\"assets/img/home.webp\" alt=\"Docaroo by PMC\">"
    collections_section:
      enabledInHome: true
      except: ["posts", "tools"] # collection name must be the one from _config.yml[collections]
      itemsToShow: 4
      collectionStartBtnText: "Start here"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
    mostRecentAndPopular_section:
      recentFilesToShow: 3
      allDocsBtnText: "Documents"
      allCatsBtnText: "Categories"
      allTagsBtnText: "Tags"
      buttonsClass: "btn-warning"
      buttonsTextClass: "text-dark"
    stats_section:
      allDocsBtnText: "Total docs"
      savedDocsBtnText: "Saved docs"
      catsBtnText: "Categories"
      pagesWithCustomsCatsBtnText: "Documents"
      tagsBtnText: "Tags"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
      buttonsIcon: "bi-arrow-right"