"/":
  enabled: true
  startPermalink: "/intro/" 
  sections:
    header_section:
      title: "Model de site pentru documentație"
      text: "Creează-ți propriul site de documentație fără niciun stres! Lasă-ți utilizatorii să preia controlul și să organizeze informațiile cum vor ei — ordonat, haotic sau undeva la mijloc. Cu instrumente de căutare ultra-rapide, vor găsi ce le trebuie mai repede decât poți zice „Unde era documentul ăla?” Documentație ușor de creat, usor de folosit și incredibil de puternică — totul într-un singur pachet bine pus la punct."
      startBtnText: "Overview"
      featuredMedia: "<img width=\"600\" height=\"auto\" src=\"assets/img/home.png\" alt=\"Docaroo by PMC\">"
    collections_section:
      enabledInHome: true
      except: ["posts"] # collection name must be the one from _config.yml[collections]
      itemsToShow: 4
      collectionStartBtnText: "Start here"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
    mostRecentAndPopular_section:
      recentFilesToShow: 3
      allDocsBtnText: "Documents"
      allCatsBtnText: "Categories"
      allTagsBtnText: "Tags"
      buttonsClass: "btn-warning"
      buttonsTextClass: "text-dark"
    stats_section:
      allDocsBtnText: "All docs"
      savedDocsBtnText: "Saved docs"
      catsBtnText: "Categories"
      pagesWithCustomsCatsBtnText: "Documents"
      tagsBtnText: "Tags"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
      buttonsIcon: "bi-arrow-right"