#!/bin/bash

 source tools_sh/colors.sh
 source tools_sh/globals.sh

 source ~/py-dev-env-392/bin/activate
 
 print_color "$YELLOW" "📋 Spell check ..."
 python3 tools_py/spell-check/spell-check.py doc-raw-contents